### ISSUE TITLE
Stolen idea from the best programmer alive

### ISSUE THREAD

**Issue by BenTearzz** [MadsLudvig/Assignments#1]
I will not hesitate to contact my lawyer and sue you for copyright infringement! For all I care you could be the pope... probably doesn't even know what ~~fucking~~ compiler is... ~~fucking~~ pope...

Since it is required by law, I'm now going to read your rights out loud _(I'm now a cop for some reason?)_. 

**You have the right to remain silent. Anything you say can and will be used against you in a court of law. You have the right to an attorney. If you cannot afford an attorney, one will be provided for you.**

Close this issue if you comply, else... I'll see you in court.

**Comment by MadsLudvig** [comment]
I fucking wrote my own compiler. Fucking CIA nigger.

**Comment by BenTearzz** [comment]
![image](https://user-images.githubusercontent.com/24865450/64940972-b155d680-d865-11e9-8f16-ae511b934048.png)

**Comment by BenTearzz** [comment]
Watch your back, you don't want to be glowing in the dark while I'm driving.
![image](https://user-images.githubusercontent.com/24865450/64942076-7012f600-d868-11e9-907f-fe3f33e5a5f5.png)
